configuration: Debug
image: Visual Studio 2022

environment:
  app_version: '3.0.0'

version: '$(app_version).{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '$(app_version).$(build_number)'
  file_version: '$(app_version).$(build_number)'
  informational_version: '$(app_version).$(build_number)'
  
cache:
  packages -> **\*.csproj  # preserve "packages" directory in the root of build folder but will reset it if a project file is modified

before_build:
 - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
 - nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
 - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: detailed

pull_requests: 
  do_not_increment_build_number: true     

nuget: 
  disable_publish_on_pr: true  

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
  - main
  - develop

test:
  assemblies:
    - OSPSuite.DataBinding.Tests.dll

skip_commits:
  files:
    - '*.md'
