name: Build and Publish

on:
  push:
    branches:
    - main

permissions:
  packages: write
  contents: read

env:
  MAJOR: 4
  MINOR: 0
  MINORMINOR: 0
  RUN: ${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          dotnet restore OSPSuite.DataBinding.sln

      - name: define env variables
        run: |
          echo "APP_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.MINORMINOR }}.${{ env.RUN }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        run: dotnet build OSPSuite.DataBinding.sln --no-restore -p:Version=${{env.APP_VERSION}}

      - name : Test
        run: dotnet test OSPSuite.DataBinding.sln -v normal --no-build --configuration Debug --logger:"html;LogFileName=../testLog_Windows.html"

      - name: Pack the project
        run: dotnet pack .\OSPSuite.DataBinding.sln --no-build --no-restore -o ./ -p:PackageVersion=${{env.APP_VERSION}} --configuration=Debug

      - name: Push test log as artifact
        uses: actions/upload-artifact@v7
        with:
          name: testLog_Windows
          path: ./**/testLog*.html

      - name: Publish to GitHub registry
        run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
